pipeline {
    agent { docker '2371da23064a' }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('deploy') {
            steps {
                input message: 'deploy the stage? (Click "Proceed" to continue)'
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the website? (Click "Proceed" to End)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
